### ISSUE TITLE
DLN api call throws INTERNAL_SERVER_ERROR due to `externalCall` param in `createDeBridgeBet`

### ISSUE THREAD

**Issue by magiclars-off** [Azuro-protocol/toolkit#4]
Quoting via `useDeBridgeBet` in azuro/sdk doesn't work. Seems related to the `externalCall` added as query param.

I don't think this param is supported (API docs: https://docs.dln.trade/dln-api/quick-start-guide/requesting-order-creation-transaction)

**line to blame:**
https://github.com/Azuro-protocol/toolkit/blob/d532befd3e5e6232fc44aedbe3520cb52ec064ef/src/utils/deBridge/createDeBridgeBet.ts#L99

**breaks:**
`https://api.dln.trade/v1.0/dln/order/create-tx?dstChainId=137&srcChainOrderAuthorityAddress=0x322e128453EFd91a4c131761d9d535fF6E0CCd90&prependOperatingExpenses=false&srcChainId=42161&srcChainTokenIn=0xaf88d065e77c8cc2239327c5edb3a432268e5831&srcChainTokenInAmount=auto&dstChainTokenOut=0xc2132d05d31c914a87c6611c10748aeb04b58e8f&dstChainTokenOutAmount=3000000&dstChainTokenOutRecipient=0x322e128453EFd91a4c131761d9d535fF6E0CCd90&dstChainOrderAuthorityAddress=0x322e128453EFd91a4c131761d9d535fF6E0CCd90&externalCall=%7B%22version%22%3A%22evm_1%22%2C%22fields%22%3A%7B%22to%22%3A%220x7043E4e1c4045424858ECBCED80989FeAfC11B36%22%2C%22data%22%3A%220xea963ec4000000000000000000000000322e128453efd91a4c131761d9d535ff6e0ccd90000000000000000000000000a40f8d69d412b79b49eabdd5cf1b5706395bfcf700000000000000000000000000000000000000000000000000000000002dc6c00000000000000000000000000000000000000000000000000000000066ab4a5d00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000e7a7981cf818e84bb6bed7eabd0c7d69ad78c9bd0000000000000000000000000000000000000000000000000000014bec61b000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000400000000000000000000000001189168e0a1690ca014cafff01c9fd3753211934000000000000000000000000000000000000000000000000000000000000001d%22%7D%7D`

**works:**
`https://api.dln.trade/v1.0/dln/order/create-tx?dstChainId=137&srcChainOrderAuthorityAddress=0x322e128453EFd91a4c131761d9d535fF6E0CCd90&prependOperatingExpenses=false&srcChainId=42161&srcChainTokenIn=0xaf88d065e77c8cc2239327c5edb3a432268e5831&srcChainTokenInAmount=auto&dstChainTokenOut=0xc2132d05d31c914a87c6611c10748aeb04b58e8f&dstChainTokenOutAmount=3000000&dstChainTokenOutRecipient=0x322e128453EFd91a4c131761d9d535fF6E0CCd90&dstChainOrderAuthorityAddress=0x322e128453EFd91a4c131761d9d535fF6E0CCd90`

**Comment by CleanBread** [comment]
Thank you for information, we'll check

**Comment by jamesonnuss** [comment]
Any update @CleanBread? Thank you

**Comment by CleanBread** [comment]
`externalCall` is a bet transaction and the main part of this feature. I'll try to contact with deBridge team

**Comment by CleanBread** [comment]
@magiclars-off @jamesonnuss 
fixed from deBridge side, now it's working
