### ISSUE TITLE
`getActiveMarkets` not returning markets for Politics when using the SDK

### ISSUE THREAD

**Issue by magiclars-off** [Azuro-protocol/toolkit#5]
When using SDK hook `useActiveMarkets` it returns no results due to some warning on the betTypeOdd which returns according to this line of code:

https://github.com/Azuro-protocol/toolkit/blob/9262be93c0bed5004f433c582d4eba7449eef239/src/utils/groupConditionsByMarket.ts#L54

```
let { markets } = useActiveMarkets({
    gameStatus: status,
    gameId: gameId,
  });
```

![image](https://github.com/user-attachments/assets/86427d3f-6754-4fc2-90a0-2835cf1eb980)

**Comment by CleanBread** [comment]
@magiclars-off try to upgrade @azuro-org/dictionaries to the latest version
