### ISSUE TITLE
DeBridge doesn't work with Gnosis

### ISSUE THREAD

**Issue by magiclars-off** [Azuro-protocol/toolkit#8]
DLN maps Gnosis chainId to `100000002` instead of `100`.

`createDeBridgeBet` should account for that

source: https://api.dln.trade/v1.0/supported-chains-info

**Comment by CleanBread** [comment]
Thanks a lot, new [release](https://github.com/Azuro-protocol/toolkit/releases/tag/v4.3.1) published

**Comment by magiclars-off** [comment]
@CleanBread  did you test it? Still doesn't work due to this line of code

![image](https://github.com/user-attachments/assets/440228e8-e4ff-466b-9e37-c2e6d0c091ff)

**Comment by CleanBread** [comment]
@magiclars-off it's problem in the SDK, not in the Toolkit. Thank you, [published fix](https://github.com/Azuro-protocol/sdk/releases/tag/v5.2.12)
